/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import DAO.AdminDAO;
import DAO.TurmaDAO;
import DAO.Conexao;
import DAO.DisciplinaDAO;
import DAO.ProfessorDAO;
import Modelo.Disciplina;
import Modelo.Turma;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author geova
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(850, 650);
        setTitle("Banco de questões");
        AtualizaCombo();
    }
    
    private void AtualizaCombo(){
        Connection con = Conexao.AbrirConexao();
        TurmaDAO sql = new TurmaDAO((com.mysql.jdbc.Connection) con);
        List<Turma> lista = new ArrayList<>();
        lista = sql.ListarComboTurma();
        jCB_turma.addItem("");
        
        for (Turma b : lista) {
            jCB_turma.addItem(b.getSerie());
        }
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCB_turma = new javax.swing.JComboBox<>();
        jtf_id_turma = new javax.swing.JTextField();
        retangulo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email_prof = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        entrar_prof = new javax.swing.JButton();
        senha_prof = new javax.swing.JPasswordField();
        retangulo_prof = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        email_adm = new javax.swing.JTextField();
        senha_adm = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_Entrar_Admin = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Turma:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 260, 250, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 70, 90, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("ENTRAR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 90, 190, 50);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 440, 130, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couple-icon-1.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 70, 90, 80);

        jCB_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_turmaActionPerformed(evt);
            }
        });
        jPanel1.add(jCB_turma);
        jCB_turma.setBounds(270, 290, 250, 50);

        jtf_id_turma.setEditable(false);
        jtf_id_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_id_turmaActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_id_turma);
        jtf_id_turma.setBounds(390, 310, 30, 20);

        retangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 3.png"))); // NOI18N
        jPanel1.add(retangulo);
        retangulo.setBounds(222, 36, 343, 500);

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(710, 20, 70, 30);

        jTabbedPane1.addTab("Aluno", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couple-icon-1.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(430, 70, 90, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("ENTRAR");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(280, 90, 190, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("E-mail:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(280, 210, 230, 30);

        email_prof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(email_prof);
        email_prof.setBounds(280, 250, 230, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Senha:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(280, 310, 230, 30);

        entrar_prof.setBackground(new java.awt.Color(0, 102, 0));
        entrar_prof.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entrar_prof.setForeground(new java.awt.Color(255, 255, 255));
        entrar_prof.setText("Entrar");
        entrar_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar_profActionPerformed(evt);
            }
        });
        jPanel2.add(entrar_prof);
        entrar_prof.setBounds(380, 440, 130, 40);
        jPanel2.add(senha_prof);
        senha_prof.setBounds(280, 350, 230, 40);

        retangulo_prof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle2.png"))); // NOI18N
        jPanel2.add(retangulo_prof);
        retangulo_prof.setBounds(225, 34, 343, 500);

        jButton5.setBackground(new java.awt.Color(153, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Sair");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(710, 20, 70, 30);

        jTabbedPane1.addTab("Professor", jPanel2);

        jPanel3.setLayout(null);

        email_adm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(email_adm);
        email_adm.setBounds(280, 210, 230, 40);

        senha_adm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(senha_adm);
        senha_adm.setBounds(280, 330, 230, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("E-mail:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(280, 170, 230, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("Senha:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(280, 290, 230, 30);

        btn_Entrar_Admin.setBackground(new java.awt.Color(255, 255, 0));
        btn_Entrar_Admin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Entrar_Admin.setText("Entrar");
        btn_Entrar_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Entrar_AdminActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Entrar_Admin);
        btn_Entrar_Admin.setBounds(380, 440, 130, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("ENTRAR");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(280, 90, 190, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone-atenção-png-1.png"))); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(430, 70, 90, 90);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 3.png"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(224, 39, 343, 500);

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(710, 20, 70, 30);

        jTabbedPane1.addTab("Admin", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String home = System.getProperty("user.home");
        String turma = jtf_id_turma.getText();
        
        if (turma.equals("")) {
            JOptionPane.showMessageDialog(null, "Nenhuma turma selecionada!",
                    "Banco de questões", JOptionPane.WARNING_MESSAGE);
        } else {

            File dir = new File(home + "/arqs");        
            File arquivo = new File(home + "/arqs/turma.txt");

            try {

                dir.mkdir();
                arquivo.createNewFile();

                FileWriter fw =  new FileWriter(arquivo, true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(turma);
                bw.close();
                fw.close();

            } catch (IOException e) {

            }

            dispose();
            new TelaAluno().setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_Entrar_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Entrar_AdminActionPerformed
        Connection con = Conexao.AbrirConexao();
        AdminDAO sql = new AdminDAO(con);
        String email = email_adm.getText();
        String senha = senha_adm.getText();
        
        if (email.equals("") || senha.equals("")) {
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio!",
                    "Banco de questões", JOptionPane.WARNING_MESSAGE);
            email_adm.setText("");
            senha_adm.setText("");
        } else {
            if (sql.Logar(email, senha) == true) {
                
                dispose();
                new TelaAdmin().setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou Senha incorreto(s)!",
                    "Banco de questões", JOptionPane.ERROR_MESSAGE);
                email_adm.setText("");
                senha_adm.setText("");
            }
        }
    }//GEN-LAST:event_btn_Entrar_AdminActionPerformed

    private void entrar_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_profActionPerformed
        Connection con = Conexao.AbrirConexao();
        ProfessorDAO sql = new ProfessorDAO((com.mysql.jdbc.Connection) con);
        String email = email_prof.getText();
        String senha = senha_prof.getText();
        
        if (email.equals("") || senha.equals("")) {
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio!",
                    "Banco de questões", JOptionPane.WARNING_MESSAGE);
            email_prof.setText("");
            senha_prof.setText("");
        } else {
            if (sql.Logar(email, senha) == true) {
                
                dispose();
                new TelaProf().setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou Senha incorreto(s)!",
                    "Banco de questões", JOptionPane.ERROR_MESSAGE);
                email_prof.setText("");
                senha_prof.setText("");
            }
        }
    }//GEN-LAST:event_entrar_profActionPerformed

    private void jCB_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_turmaActionPerformed
        Connection con = Conexao.AbrirConexao();
        TurmaDAO sql = new TurmaDAO((com.mysql.jdbc.Connection) con);
        List<Turma> lista = new ArrayList<>();
        String nome = jCB_turma.getSelectedItem().toString();

        lista = sql.ConsultaCodigoTurma(nome);

        for (Turma b : lista) {
            int a = b.getId();
            jtf_id_turma.setText("" + a);
        }
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }//GEN-LAST:event_jCB_turmaActionPerformed

    private void jtf_id_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_id_turmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_id_turmaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrar_Admin;
    private javax.swing.JTextField email_adm;
    private javax.swing.JTextField email_prof;
    private javax.swing.JButton entrar_prof;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jCB_turma;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jtf_id_turma;
    private javax.swing.JLabel retangulo;
    private javax.swing.JLabel retangulo_prof;
    private javax.swing.JPasswordField senha_adm;
    private javax.swing.JPasswordField senha_prof;
    // End of variables declaration//GEN-END:variables
}
