/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import DAO.AdminDAO;
import DAO.Conexao;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author geova
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(850, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        senha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        retangulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        senha1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        retangulo_prof = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        email_adm = new javax.swing.JTextField();
        senha_adm = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_Entrar_Admin = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("E-mail:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 210, 230, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 70, 90, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("ENTRAR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 90, 190, 50);

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(email);
        email.setBounds(280, 250, 230, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Senha:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 310, 230, 30);

        senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(senha);
        senha.setBounds(280, 350, 230, 40);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 440, 130, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couple-icon-1.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 70, 90, 80);

        retangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 3.png"))); // NOI18N
        jPanel1.add(retangulo);
        retangulo.setBounds(222, 36, 343, 500);

        jTabbedPane1.addTab("Aluno", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couple-icon-1.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(430, 70, 90, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("ENTRAR");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(280, 90, 190, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("E-mail:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(280, 210, 230, 30);

        email1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(email1);
        email1.setBounds(280, 250, 230, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Senha:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(280, 310, 230, 30);

        senha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(senha1);
        senha1.setBounds(280, 350, 230, 40);

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Entrar");
        jPanel2.add(jButton2);
        jButton2.setBounds(380, 440, 130, 40);

        retangulo_prof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle2.png"))); // NOI18N
        jPanel2.add(retangulo_prof);
        retangulo_prof.setBounds(225, 34, 343, 500);

        jTabbedPane1.addTab("Professor", jPanel2);

        jPanel3.setLayout(null);

        email_adm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(email_adm);
        email_adm.setBounds(280, 210, 230, 40);

        senha_adm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.add(senha_adm);
        senha_adm.setBounds(280, 330, 230, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("E-mail:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(280, 170, 230, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("Senha:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(280, 290, 230, 30);

        btn_Entrar_Admin.setBackground(new java.awt.Color(255, 255, 0));
        btn_Entrar_Admin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Entrar_Admin.setText("Entrar");
        btn_Entrar_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Entrar_AdminActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Entrar_Admin);
        btn_Entrar_Admin.setBounds(380, 440, 130, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("ENTRAR");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(280, 90, 190, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone-atenção-png-1.png"))); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(430, 70, 90, 90);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 3.png"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(224, 39, 343, 500);

        jTabbedPane1.addTab("Admin", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_Entrar_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Entrar_AdminActionPerformed
        Connection con = Conexao.AbrirConexao();
        AdminDAO sql = new AdminDAO(con);
        String email = email_adm.getText();
        String senha = senha_adm.getText();
        
        if (email.equals("") || senha.equals("")) {
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio!",
                    "Banco de questões", JOptionPane.WARNING_MESSAGE);
            email_adm.setText("");
            senha_adm.setText("");
        } else {
            if (sql.Logar(email, senha) == true) {
                
                dispose();
                new TelaAdmin().setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou Senha incorreto(s)!",
                    "Banco de questões", JOptionPane.ERROR_MESSAGE);
                email_adm.setText("");
                senha_adm.setText("");
            }
        }
    }//GEN-LAST:event_btn_Entrar_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrar_Admin;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField email_adm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel retangulo;
    private javax.swing.JLabel retangulo_prof;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField senha1;
    private javax.swing.JPasswordField senha_adm;
    // End of variables declaration//GEN-END:variables
}
