/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import DAO.AssuntoDAO;
import DAO.Conexao;
import DAO.DisciplinaDAO;
import DAO.ProvaDAO;
import DAO.QuestaoDAO;
import Modelo.Aluno;
import Modelo.Assunto;
import Modelo.Disciplina;
import Modelo.Prova;
import Modelo.Questao;
import Views.Excluir.excluir_prova;
import Views.Alterar.*;
import Views.Cadastrar.*;
import Views.Consultar.*;
import Views.Excluir.*;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author geova
 */
public class TelaAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmin
     */
    public TelaAluno() {
        initComponents();
        AtualizaCombo();
        AtualizaTable();
        AtualizaTable1();
    }
    
    private void AtualizaTable1() {
        Connection con = Conexao.AbrirConexao();
        QuestaoDAO bd = new QuestaoDAO((com.mysql.jdbc.Connection) con);
        List<Questao> lista = new ArrayList<>();
        lista = bd.Listar_Questao_Consulta();
        DefaultTableModel tbm = (DefaultTableModel) jTable1.getModel();
        
        while (tbm.getRowCount() > 0) {
            tbm.removeRow(0);
        }
        
        int i = 0;
        for (Questao tab : lista) {
            tbm.addRow(new String[i]);
            jTable1.setValueAt(tab.getId(), i, 0);
            jTable1.setValueAt(tab.getId_disc(), i, 1);
            jTable1.setValueAt(tab.getId_assu(), i, 2);
            jTable1.setValueAt(tab.getEnun(), i, 3);
            jTable1.setValueAt(tab.getGab(), i, 4);
            i++;
        }
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }
    
    private void AtualizaTable() {
        Connection con = Conexao.AbrirConexao();
        AssuntoDAO bd = new AssuntoDAO((com.mysql.jdbc.Connection) con);
        List<Assunto> lista = new ArrayList<>();
        lista = bd.Listar_Assunto_Consulta();
        DefaultTableModel tbm = (DefaultTableModel) jTable.getModel();
        
        while (tbm.getRowCount() > 0) {
            tbm.removeRow(0);
        }
        
        int i = 0;
        for (Assunto tab : lista) {
            tbm.addRow(new String[i]);
            jTable.setValueAt(tab.getId(), i, 0);
            jTable.setValueAt(tab.getNome(), i, 1);
            jTable.setValueAt(tab.getId_disc(), i, 2);
            i++;
        }
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }

    private void AtualizaCombo(){
//        String home = System.getProperty("user.home");
//        File arquivo = new File(home + "/arqs/turma.txt");
//        String p = "";
//        
//        try {
//            FileReader fr = new FileReader(arquivo);
//            BufferedReader br = new BufferedReader(fr);
//
//            String linha = br.readLine();
//
//            while(linha != null){
//                p += linha;
//                linha = br.readLine();
//            }
//        }catch(IOException e){
//            
//           JOptionPane.showMessageDialog(null, e);
//        }
//        
//        int id_turma = Integer.parseInt(p);
        Connection con = Conexao.AbrirConexao();
        QuestaoDAO sql = new QuestaoDAO((com.mysql.jdbc.Connection) con);
        List<Questao> lista = new ArrayList<>();
        lista = sql.ListarComboQuestao();
        jCB_turma.addItem("");
        
        for (Questao b : lista) {
            jCB_turma.addItem(""+b.getId());
        }
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jCB_turma = new javax.swing.JComboBox<>();
        jtf_id_turma = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_cad_disc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(450, 30, 70, 20);

        jCB_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_turmaActionPerformed(evt);
            }
        });
        jPanel1.add(jCB_turma);
        jCB_turma.setBounds(60, 190, 250, 40);

        jtf_id_turma.setEditable(false);
        jtf_id_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_id_turmaActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_id_turma);
        jtf_id_turma.setBounds(180, 200, 30, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("Código da questão:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 150, 230, 30);

        btn_cad_disc.setBackground(new java.awt.Color(255, 255, 0));
        btn_cad_disc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cad_disc.setText("Gerar Questão");
        btn_cad_disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cad_discActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cad_disc);
        btn_cad_disc.setBounds(340, 190, 150, 40);

        jTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Código Disciplina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 280, 190, 250);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código Disciplina", "Código Assunto", "Enunciado", "Gabarito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(230, 280, 520, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 105);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Principal.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 750, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String home = System.getProperty("user.home");    
        File arquivo = new File(home + "/arqs/turma.txt");

            try {

            boolean a = arquivo.delete();
                if (a) {
                    JOptionPane.showMessageDialog(null, "Apagado");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro");
                }

            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Erro");
            }
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCB_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_turmaActionPerformed
        Connection con = Conexao.AbrirConexao();
        QuestaoDAO sql = new QuestaoDAO((com.mysql.jdbc.Connection) con);
        List<Questao> lista = new ArrayList<>();
        String nome = jCB_turma.getSelectedItem().toString();

        lista = sql.ConsultaCodigoQuestao(nome);

        for (Questao b : lista) {
            int a = b.getId();
            jtf_id_turma.setText("" + a);
        }
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }//GEN-LAST:event_jCB_turmaActionPerformed

    private void jtf_id_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_id_turmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_id_turmaActionPerformed

    private void btn_cad_discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cad_discActionPerformed
    Connection con = Conexao.AbrirConexao();
    QuestaoDAO sql = new QuestaoDAO((com.mysql.jdbc.Connection) con);
    List<Questao> lista = new ArrayList<>();
    
    String home = System.getProperty("user.home");
    String id = jtf_id_turma.getText();
    int id_pro = Integer.parseInt(id);
    
    lista = sql.Gerar_Questao(id_pro);

    for (Questao b : lista) {     
            File arquivo = new File(home + "/Document/questao"+ b.getId() +".txt");

            try {
                arquivo.createNewFile();
                FileWriter fw =  new FileWriter(arquivo, true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write("Código da questão: "+ b.getId() +"\n"
                        +"Código da disciplina: "+ b.getId_disc()+"\n"
                        +"Código do assunto: "+ b.getId_assu()+"\n \n \n"
                        + b.getEnun() + "\n \n"
                        + b.getAlt1() + "\n"
                        + b.getAlt2() + "\n"
                        + b.getAlt3() + "\n"
                        + b.getAlt4() + "\n");
                bw.close();
                fw.close();
            
            JOptionPane.showMessageDialog(null, "Questão na pasta (Documentos) do seu computador", 
                                            "Banco de questões", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {

            }
    }
    Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }//GEN-LAST:event_btn_cad_discActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cad_disc;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCB_turma;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtf_id_turma;
    // End of variables declaration//GEN-END:variables
}
