/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author geova
 */
public class TelaProf extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmin
     */
    public TelaProf() {
        initComponents();
        LimparTela();
    }

    public void LimparTela() {
        cad_questao.setVisible(false);
        cad_prova.setVisible(false);
        cad_assunto.setVisible(false);
        alt_questao.setVisible(false);
        alt_prova.setVisible(false);
        alt_assunto.setVisible(false);
        cons_questao.setVisible(false);
        cons_prova.setVisible(false);
        cons_assunto.setVisible(false);
        exc_questao.setVisible(false);
        exc_prova.setVisible(false);
        exc_assunto.setVisible(false);
    }
    
    public void questao() {
        cad_questao.setVisible(true);
        cad_prova.setVisible(false);
        cad_assunto.setVisible(false);
        alt_questao.setVisible(true);
        alt_prova.setVisible(false);
        alt_assunto.setVisible(false);
        cons_questao.setVisible(true);
        cons_prova.setVisible(false);
        cons_assunto.setVisible(false);
        exc_questao.setVisible(true);
        exc_prova.setVisible(false);
        exc_assunto.setVisible(false);
    }
    public void prova() {
        cad_questao.setVisible(false);
        cad_prova.setVisible(true);
        cad_assunto.setVisible(false);
        alt_questao.setVisible(false);
        alt_prova.setVisible(true);
        alt_assunto.setVisible(false);
        cons_questao.setVisible(false);
        cons_prova.setVisible(true);
        cons_assunto.setVisible(false);
        exc_questao.setVisible(false);
        exc_prova.setVisible(true);
        exc_assunto.setVisible(false);
    }
    public void assunto() {
        cad_questao.setVisible(false);
        cad_prova.setVisible(false);
        cad_assunto.setVisible(true);
        alt_questao.setVisible(false);
        alt_prova.setVisible(false);
        alt_assunto.setVisible(true);
        cons_questao.setVisible(false);
        cons_prova.setVisible(false);
        cons_assunto.setVisible(true);
        exc_questao.setVisible(false);
        exc_prova.setVisible(false);
        exc_assunto.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Questao = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_Prova = new javax.swing.JButton();
        btn_Assunto = new javax.swing.JButton();
        cad_prova = new javax.swing.JButton();
        alt_prova = new javax.swing.JButton();
        cons_prova = new javax.swing.JButton();
        exc_prova = new javax.swing.JButton();
        cad_questao = new javax.swing.JButton();
        alt_questao = new javax.swing.JButton();
        cons_questao = new javax.swing.JButton();
        exc_questao = new javax.swing.JButton();
        cad_assunto = new javax.swing.JButton();
        alt_assunto = new javax.swing.JButton();
        exc_assunto = new javax.swing.JButton();
        cons_assunto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        btn_Questao.setBackground(new java.awt.Color(0, 153, 0));
        btn_Questao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Questao.setForeground(new java.awt.Color(255, 255, 255));
        btn_Questao.setText("Questão");
        btn_Questao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuestaoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Questao);
        btn_Questao.setBounds(150, 20, 120, 40);

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sair");
        jPanel1.add(jButton3);
        jButton3.setBounds(450, 30, 70, 20);

        btn_Prova.setBackground(new java.awt.Color(0, 153, 0));
        btn_Prova.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Prova.setForeground(new java.awt.Color(255, 255, 255));
        btn_Prova.setText("Prova");
        btn_Prova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProvaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Prova);
        btn_Prova.setBounds(10, 20, 110, 40);

        btn_Assunto.setBackground(new java.awt.Color(0, 153, 0));
        btn_Assunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Assunto.setForeground(new java.awt.Color(255, 255, 255));
        btn_Assunto.setText("Assunto");
        btn_Assunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AssuntoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Assunto);
        btn_Assunto.setBounds(300, 20, 120, 40);

        cad_prova.setBackground(new java.awt.Color(0, 153, 0));
        cad_prova.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cad_prova.setText("Cadastrar Prova");
        cad_prova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_provaActionPerformed(evt);
            }
        });
        jPanel1.add(cad_prova);
        cad_prova.setBounds(120, 210, 210, 100);

        alt_prova.setBackground(new java.awt.Color(0, 153, 0));
        alt_prova.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alt_prova.setText("Alterar Prova");
        alt_prova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_provaActionPerformed(evt);
            }
        });
        jPanel1.add(alt_prova);
        alt_prova.setBounds(460, 210, 210, 100);

        cons_prova.setBackground(new java.awt.Color(0, 153, 0));
        cons_prova.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cons_prova.setText("Consultar Prova");
        cons_prova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_provaActionPerformed(evt);
            }
        });
        jPanel1.add(cons_prova);
        cons_prova.setBounds(120, 380, 210, 100);

        exc_prova.setBackground(new java.awt.Color(0, 153, 0));
        exc_prova.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exc_prova.setText("Excluir Prova");
        exc_prova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_provaActionPerformed(evt);
            }
        });
        jPanel1.add(exc_prova);
        exc_prova.setBounds(460, 380, 210, 100);

        cad_questao.setBackground(new java.awt.Color(0, 153, 0));
        cad_questao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cad_questao.setText("Cadastrar Questão");
        cad_questao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_questaoActionPerformed(evt);
            }
        });
        jPanel1.add(cad_questao);
        cad_questao.setBounds(120, 210, 210, 100);

        alt_questao.setBackground(new java.awt.Color(0, 153, 0));
        alt_questao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alt_questao.setText("Alterar Questão");
        alt_questao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_questaoActionPerformed(evt);
            }
        });
        jPanel1.add(alt_questao);
        alt_questao.setBounds(460, 210, 210, 100);

        cons_questao.setBackground(new java.awt.Color(0, 153, 0));
        cons_questao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cons_questao.setText("Consultar Questão");
        cons_questao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_questaoActionPerformed(evt);
            }
        });
        jPanel1.add(cons_questao);
        cons_questao.setBounds(120, 380, 210, 100);

        exc_questao.setBackground(new java.awt.Color(0, 153, 0));
        exc_questao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exc_questao.setText("Excluir Questão");
        exc_questao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_questaoActionPerformed(evt);
            }
        });
        jPanel1.add(exc_questao);
        exc_questao.setBounds(460, 380, 210, 100);

        cad_assunto.setBackground(new java.awt.Color(0, 153, 0));
        cad_assunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cad_assunto.setText("Cadastrar Assunto");
        cad_assunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_assuntoActionPerformed(evt);
            }
        });
        jPanel1.add(cad_assunto);
        cad_assunto.setBounds(120, 210, 210, 100);

        alt_assunto.setBackground(new java.awt.Color(0, 153, 0));
        alt_assunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alt_assunto.setText("Alterar Assunto");
        alt_assunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_assuntoActionPerformed(evt);
            }
        });
        jPanel1.add(alt_assunto);
        alt_assunto.setBounds(460, 210, 210, 100);

        exc_assunto.setBackground(new java.awt.Color(0, 153, 0));
        exc_assunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exc_assunto.setText("Excluir Assunto");
        exc_assunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_assuntoActionPerformed(evt);
            }
        });
        jPanel1.add(exc_assunto);
        exc_assunto.setBounds(460, 380, 210, 100);

        cons_assunto.setBackground(new java.awt.Color(0, 153, 0));
        cons_assunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cons_assunto.setText("Consultar Assunto");
        cons_assunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_assuntoActionPerformed(evt);
            }
        });
        jPanel1.add(cons_assunto);
        cons_assunto.setBounds(120, 380, 210, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 105);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Principal.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 750, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProvaActionPerformed
        prova();
    }//GEN-LAST:event_btn_ProvaActionPerformed

    private void btn_AssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AssuntoActionPerformed
        assunto();
    }//GEN-LAST:event_btn_AssuntoActionPerformed

    private void cad_provaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_provaActionPerformed
        dispose();
        new cadastrar_prova().setVisible(true);
    }//GEN-LAST:event_cad_provaActionPerformed

    private void alt_provaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_provaActionPerformed
        dispose();
        new alterar_prova().setVisible(true);
    }//GEN-LAST:event_alt_provaActionPerformed

    private void cons_provaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_provaActionPerformed
        dispose();
        new consultar_prova().setVisible(true);
    }//GEN-LAST:event_cons_provaActionPerformed

    private void exc_provaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_provaActionPerformed
        dispose();
        new excluir_prova().setVisible(true);
    }//GEN-LAST:event_exc_provaActionPerformed

    private void cad_questaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_questaoActionPerformed
        dispose();
        new cadastrar_questao().setVisible(true);
    }//GEN-LAST:event_cad_questaoActionPerformed

    private void alt_questaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_questaoActionPerformed
        dispose();
        new alterar_questao().setVisible(true);
    }//GEN-LAST:event_alt_questaoActionPerformed

    private void cons_questaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_questaoActionPerformed
        dispose();
        new consultar_questao().setVisible(true);
    }//GEN-LAST:event_cons_questaoActionPerformed

    private void exc_questaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_questaoActionPerformed
        dispose();
        new excluir_questao().setVisible(true);
    }//GEN-LAST:event_exc_questaoActionPerformed

    private void cad_assuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_assuntoActionPerformed
        dispose();
        new cadastrar_assunto().setVisible(true);
    }//GEN-LAST:event_cad_assuntoActionPerformed

    private void alt_assuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_assuntoActionPerformed
        dispose();
        new alterar_assunto().setVisible(true);
    }//GEN-LAST:event_alt_assuntoActionPerformed

    private void exc_assuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_assuntoActionPerformed
        dispose();
        new excluir_assunto().setVisible(true);
    }//GEN-LAST:event_exc_assuntoActionPerformed

    private void cons_assuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_assuntoActionPerformed
        dispose();
        new consultar_assunto().setVisible(true);
    }//GEN-LAST:event_cons_assuntoActionPerformed

    private void btn_QuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuestaoActionPerformed
        questao();
    }//GEN-LAST:event_btn_QuestaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alt_assunto;
    private javax.swing.JButton alt_prova;
    private javax.swing.JButton alt_questao;
    private javax.swing.JButton btn_Assunto;
    private javax.swing.JButton btn_Prova;
    private javax.swing.JButton btn_Questao;
    private javax.swing.JButton cad_assunto;
    private javax.swing.JButton cad_prova;
    private javax.swing.JButton cad_questao;
    private javax.swing.JButton cons_assunto;
    private javax.swing.JButton cons_prova;
    private javax.swing.JButton cons_questao;
    private javax.swing.JButton exc_assunto;
    private javax.swing.JButton exc_prova;
    private javax.swing.JButton exc_questao;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
