/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Alterar;

import Views.Cadastrar.*;
import DAO.Conexao;
import DAO.DisciplinaDAO;
import DAO.ProfessorDAO;
import Modelo.Disciplina;
import Modelo.Professor;
import Principal.*;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author geova
 */
public class alterar_professor extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmin
     */
    public alterar_professor() {
        initComponents();
        AtualizaCombo();
    }

    private void InserirDados(int id){
        Connection con = Conexao.AbrirConexao();
        ProfessorDAO sql = new ProfessorDAO((com.mysql.jdbc.Connection) con);
        List<Professor> lista = new ArrayList<>();
        lista = sql.Pegar_Professor(id);
        
        for (Professor a : lista) {
            id_prof.setText("" + a.getId());
            nome_prof.setText("" + a.getNome());
            email_prof.setText("" + a.getEmail());
            senha_prof.setText("" + a.getSenha());
            
        }
        
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }
        
    private void AtualizaCombo(){
        Connection con = Conexao.AbrirConexao();
        DisciplinaDAO sql = new DisciplinaDAO((com.mysql.jdbc.Connection) con);
        List<Disciplina> lista = new ArrayList<>();
        lista = sql.ListarComboDisciplina();
        jCB_disc.addItem("");
        
        for (Disciplina b : lista) {
            jCB_disc.addItem(b.getNome());
        }
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btn_alt_prof = new javax.swing.JButton();
        id_professor = new javax.swing.JTextField();
        btn_pesq_disc = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        id_prof = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        email_prof = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        senha_prof = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jtf_id_disc = new javax.swing.JTextField();
        jCB_disc = new javax.swing.JComboBox<>();
        nome_prof = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Turma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 20, 120, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Disciplina");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 20, 120, 40);

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sair");
        jPanel1.add(jButton3);
        jButton3.setBounds(450, 30, 70, 20);

        jButton4.setBackground(new java.awt.Color(255, 255, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Professor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 20, 120, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Digite o código do professor:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(150, 210, 230, 30);

        btn_alt_prof.setBackground(new java.awt.Color(255, 255, 0));
        btn_alt_prof.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_alt_prof.setText("Alterar");
        btn_alt_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alt_profActionPerformed(evt);
            }
        });
        jPanel1.add(btn_alt_prof);
        btn_alt_prof.setBounds(160, 430, 200, 70);

        id_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_professorActionPerformed(evt);
            }
        });
        jPanel1.add(id_professor);
        id_professor.setBounds(150, 250, 130, 40);

        btn_pesq_disc.setBackground(new java.awt.Color(255, 255, 102));
        btn_pesq_disc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_pesq_disc.setText("Pesquisar");
        btn_pesq_disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesq_discActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pesq_disc);
        btn_pesq_disc.setBounds(290, 250, 90, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("Código:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(460, 150, 230, 30);

        id_prof.setEditable(false);
        id_prof.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(id_prof);
        id_prof.setBounds(460, 180, 230, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("E-mail:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(460, 310, 230, 30);

        email_prof.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(email_prof);
        email_prof.setBounds(460, 340, 230, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setText("Senha:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(460, 390, 230, 30);
        jPanel1.add(senha_prof);
        senha_prof.setBounds(460, 420, 230, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 51));
        jLabel15.setText("Matéria:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(460, 470, 230, 30);

        jtf_id_disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_id_discActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_id_disc);
        jtf_id_disc.setBounds(460, 500, 50, 30);

        jCB_disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_discActionPerformed(evt);
            }
        });
        jPanel1.add(jCB_disc);
        jCB_disc.setBounds(520, 500, 170, 30);

        nome_prof.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(nome_prof);
        nome_prof.setBounds(460, 260, 230, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 51));
        jLabel16.setText("Nome:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(460, 230, 230, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuAdmin.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 105);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Principal (1).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 750, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new TelaAdmin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        new TelaAdmin().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new TelaAdmin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_alt_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alt_profActionPerformed
    String codigo = id_prof.getText();
    String nome = nome_prof.getText();
    String email = email_prof.getText();
    String senha = senha_prof.getText();
    String disc = jtf_id_disc.getText();
    
    if (nome.equals("") || email.equals("") || senha.equals("") || disc.equals("")) {
        JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio!",
                    "Banco de questões", JOptionPane.WARNING_MESSAGE);
    } else {
        Connection con = Conexao.AbrirConexao();
        ProfessorDAO sql = new ProfessorDAO((com.mysql.jdbc.Connection) con);
        int cod = Integer.parseInt(codigo);
        int id_disc = Integer.parseInt(disc);
        Professor a = new Professor();
        
        a.setId(cod);
        a.setNome(nome);
        a.setEmail(email);
        a.setSenha(senha);
        a.setId_disc(id_disc);
        
        
        sql.Alterar_Professor(a);
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);

        id_professor.setText("");
        id_prof.setText("");
        nome_prof.setText("");
        email_prof.setText("");
        senha_prof.setText("");
        jtf_id_disc.setText("");
        jCB_disc.setSelectedIndex(0);
        
        JOptionPane.showMessageDialog(null, "Professor alterado com sucesso!",
                    "Banco de questões", JOptionPane.INFORMATION_MESSAGE);   
    }
    }//GEN-LAST:event_btn_alt_profActionPerformed

    private void btn_pesq_discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesq_discActionPerformed
    String id = id_professor.getText();
    Connection con = Conexao.AbrirConexao();
    ProfessorDAO sql = new ProfessorDAO((com.mysql.jdbc.Connection) con);
    int cod = Integer.parseInt(id);
    
        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um código para atualizar",
                        "Banco de questões", JOptionPane.WARNING_MESSAGE);
        }
        
            id_prof.setText("");
            id_prof.setText("");
            nome_prof.setText("");
            email_prof.setText("");
            senha_prof.setText("");

            
    InserirDados(cod);
    id_professor.setText("");
    }//GEN-LAST:event_btn_pesq_discActionPerformed

    private void jtf_id_discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_id_discActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_id_discActionPerformed

    private void jCB_discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_discActionPerformed
        Connection con = Conexao.AbrirConexao();
        DisciplinaDAO sql = new DisciplinaDAO((com.mysql.jdbc.Connection) con);
        List<Disciplina> lista = new ArrayList<>();
        String nome = jCB_disc.getSelectedItem().toString();

        lista = sql.ConsultaCodigoDisc(nome);

        for (Disciplina b : lista) {
            int a = b.getId();
            jtf_id_disc.setText("" + a);
        }
        Conexao.FecharConexao((com.mysql.jdbc.Connection) con);
    }//GEN-LAST:event_jCB_discActionPerformed

    private void id_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_professorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_professorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterar_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterar_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterar_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterar_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterar_professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alt_prof;
    private javax.swing.JButton btn_pesq_disc;
    private javax.swing.JTextField email_prof;
    private javax.swing.JTextField id_prof;
    private javax.swing.JTextField id_professor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCB_disc;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtf_id_disc;
    private javax.swing.JTextField nome_prof;
    private javax.swing.JPasswordField senha_prof;
    // End of variables declaration//GEN-END:variables
}
